[package]
name = "v850-svd"
version = "0.1.0"
authors = ["Roman Valls Guimera <brainstorm@nopcode.org>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.123", features = [ "derive" ] }
quick-xml = { version = "0.21.0", features = [ "serialize" ] }
