[package]
name = "datasheet2svd"
version = "0.1.0"
authors = ["Roman Valls Guimera <brainstorm@nopcode.org>"]
edition = "2018"

[dependencies]
yaserde = { version = "0.8" }
yaserde_derive = { version = "0.8" }
serde = { version = "1", features = ["derive"] }
xml-rs = "0.8"
log = "0.4"
csv = "1"
